#!/bin/bash
clear
menu_adm1 (){
echo -e "\033[0;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[1;92m       #-->--#   MENU DE OPCIONES   #--<--#          \E[0m"
echo -e "\033[0;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mADMINISTRAR USUARIOS v1\E[0m \E[1;36m>>\E[0m\E[3;31mSSH/WS/UDP... \E[0m<<"
echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mADMINISTRAR USUARIOS v2\E[0m \E[1;36m>>\E[0m\E[3;31mSSH/WS/UDP...\E[0m<<"
echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mADMINISTRAR USUARIOS\E[0m \E[1;36m>>\E[0m\E[3;31mHWID\E[0m<<"
echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mADMINISTRAR USUARIOS\E[0m \E[1;36m>>\E[0m\E[3;31mTOKEN v2\E[0m<<"
echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mADMINISTRAR USUARIOS\E[0m \E[1;36m>>\E[0m\E[3;31mTOKEN v2\E[0m<<"
echo -e "\033[1;31m[\033[1;36m6\033[1;31m] \033[1;37m• \033[1;33mADMINISTRAR USUARIOS\E[0m \E[1;36m>>\E[0m\E[3;31mV2RAY\E[0m<<"
echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \e[97m\033[1;41mVOLVER"
echo -e "\033[0;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -ne "\033[1;92m➜ INGRESE UNA OPCION: \033[1;37m "; read option
case $option in 

      1)  
      clear
      admsshplus ;;
      2) 
      clear
      bash <(curl -sL https://raw.githubusercontent.com/gitter75/HERRAMIENTAS/main/HERRAMIENTAS/USERSSHV2)
      ;;
      3) 
      clear
      bash <(curl -sL https://raw.githubusercontent.com/jorgevps10/modulosbin/main/HWID.bin)
      ;;
      4)
      clear
      bash <(curl -sL https://raw.githubusercontent.com/jorgevps10/modulosbin/main/TOKENV1.bin)
      ;;
      5)
      clear
      bash <(curl -sL https://raw.githubusercontent.com/gitter75/HERRAMIENTAS/main/HERRAMIENTAS/USERTOKENV2)
      ;;
      6)
      clear
      bash <(curl -sL https://raw.githubusercontent.com/gitter75/HERRAMIENTAS/main/HERRAMIENTAS/USERV2RAY)
      ;;
      0)
      echo -e "\033[1;31mSALIENDO...\033[0m"
      sleep 2
      clear
      admuser ;;
      *)
      echo -e "\n\033[1;31mOPCION INVALIDA !\033[0m"
      sleep 2
esac
}
